-- MySQL Script generated by MySQL Workbench
-- Wed 15 Jan 2020 11:59:06 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Medical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical` (
  `Medical_id` VARCHAR(45) NOT NULL,
  `Overtime_rate` INT NULL,
  PRIMARY KEY (`Medical_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specialist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specialist` (
  `Specialist_id` VARCHAR(50) NOT NULL,
  `Field_area` INT NULL,
  PRIMARY KEY (`Specialist_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `Doctor_id` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(70) NULL,
  `Date_of_Birth` DATE NULL,
  `Address` VARCHAR(100) NULL,
  `phone_number` INT(20) NULL,
  `salary` VARCHAR(45) NULL,
  `Medical_id` VARCHAR(45) COLLATE 'Default Collation' NULL,
  `Specialist_id` VARCHAR(50) NULL,
  PRIMARY KEY (`Doctor_id`),
  INDEX `Medical_idx` (`Medical_id` ASC) VISIBLE,
  INDEX `Specialist_idx` (`Specialist_id` ASC) VISIBLE,
  CONSTRAINT `Medical`
    FOREIGN KEY (`Medical_id`)
    REFERENCES `mydb`.`Medical` (`Medical_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Specialist`
    FOREIGN KEY (`Specialist_id`)
    REFERENCES `mydb`.`Specialist` (`Specialist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `Patient_id` VARCHAR(45) NOT NULL,
  `Name` INT NULL,
  `Address` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `Date_of_Birth` DATE NULL,
  PRIMARY KEY (`Patient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `Appointment_id` VARCHAR(45) NOT NULL,
  `Date` DATE NULL,
  `Time` VARCHAR(45) NULL,
  `Doctor_id` VARCHAR(45) NULL,
  `Patient_id` VARCHAR(45) NULL,
  PRIMARY KEY (`Appointment_id`),
  INDEX `Doctor_idx` (`Doctor_id` ASC) VISIBLE,
  INDEX `Patient_idx` (`Patient_id` ASC) VISIBLE,
  CONSTRAINT `Doctor`
    FOREIGN KEY (`Doctor_id`)
    REFERENCES `mydb`.`Doctor` (`Doctor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Patient`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `mydb`.`Patient` (`Patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `Payment_id` VARCHAR(45) NOT NULL,
  `Details` VARCHAR(45) NULL,
  `Method` VARCHAR(45) NULL,
  PRIMARY KEY (`Payment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `Bill_id` VARCHAR(45) NOT NULL,
  `Total` VARCHAR(45) NULL,
  `Patient_id` VARCHAR(45) NULL,
  PRIMARY KEY (`Bill_id`),
  INDEX `Bill_idx` (`Patient_id` ASC) VISIBLE,
  CONSTRAINT `Bill`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `mydb`.`Patient` (`Patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment_for_Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment_for_Bill` (
  `Name` VARCHAR(45) NOT NULL,
  `Bill_id` VARCHAR(45) NULL,
  `Payment_id` VARCHAR(45) NULL,
  PRIMARY KEY (`Name`),
  INDEX `Payment_idx` (`Payment_id` ASC) VISIBLE,
  CONSTRAINT `Bill`
    FOREIGN KEY (`Bill_id`)
    REFERENCES `mydb`.`Bill` (`Bill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Payment`
    FOREIGN KEY (`Payment_id`)
    REFERENCES `mydb`.`Payment` (`Payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
